name: Use output
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Runner Setup
        uses: ./.github/actions/runner_setup

      - name: Step one
        id: step_one
        run: echo project_version=$(mvn help:evaluate -Dexpression="project.version" -q -DforceStdout) >> $GITHUB_ENV
    
      - name: Step two
        run: "echo 'Version: $project_version"
